### ISSUE TITLE
Describe how to get the correct git branch in README

### ISSUE THREAD

**Issue by gitressa** [anavarre/d9#1]
Great work, thanks!

To quickly test it, I got it running with this minimal number of commands:
```
git clone git@github.com:anavarre/d9.git
git clone https://git.drupalcode.org/project/drupal.git
cd drupal
../d9/d9.py --install
```
... which works perfectly, but gets me 8.8.3-dev.

If I start with this

`git clone --branch 9.0.x https://git.drupalcode.org/project/drupal.git`

... I get this error, and the installation fails:

> ===> Pulling Composer dependencies
> Your requirements could not be resolved to an installable set of packages.

Is [Setting up repository for the first time](https://www.drupal.org/node/3060/git-instructions/9.0.x/nonmaintainer) not the the correct way? Perhaps the correct way to git clone Drupal 9 could get included in the project README?

**Comment by anavarre** [comment]
>... which works perfectly, but gets me 8.8.3-dev.

Aha. It's not you, it's me. It should never have worked against a Drupal 8 checkout. It means I have a bug in the logic.

I'll fix this in a moment, sorry! And thanks for finding this out.

**Comment by gitressa** [comment]
Thanks! It's awesome that the detection is more precise now. But this issue was more directed towards figuring out how to get the correct code, and possibly adding it as a first step in the README file? Or perhaps you are fixing that as I write, and I need to be more patient? :-)

**Comment by anavarre** [comment]
Hopefully I've done both in 5c4dfe9 so we're extra cautious. I've clarified the README file and also improved the logic to better catch any issue with the branch that is checked out upon running the script.

**Comment by gitressa** [comment]
Thanks for expanding the README instructions. However, I still get an error:

```
$ git clone git@github.com:anavarre/d9.git
Cloning into 'd9'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 23 (delta 8), reused 19 (delta 5), pack-reused 0
Receiving objects: 100% (23/23), 18.28 KiB | 9.14 MiB/s, done.
Resolving deltas: 100% (8/8), done.

$ git clone --branch 9.0.x https://git.drupalcode.org/project/drupal.git
Cloning into 'drupal'...
remote: Enumerating objects: 2117, done.
remote: Counting objects: 100% (2117/2117), done.
remote: Compressing objects: 100% (1152/1152), done.
remote: Total 721048 (delta 1032), reused 1921 (delta 934), pack-reused 718931
Receiving objects: 100% (721048/721048), 160.25 MiB | 29.05 MiB/s, done.
Resolving deltas: 100% (523570/523570), done.

$ cd drupal/

$ ../d9/d9.py --install
===> Drupal 9 codebase detected
===> Git repository detected
===> Drupal 9 branch detected
===> composer.json detected
===> Pulling Composer dependencies
Your requirements could not be resolved to an installable set of packages.
===> Installing the latest Drush
Your requirements could not be resolved to an installable set of packages.
===> Creating Lando configuration file (PHP 7.3 / MySQL 5.7)
===> Starting app
Let's get this party started! Starting app..
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "drupal9_default" with the default driver
Creating volume "drupal9_data_appserver" with default driver
Creating volume "drupal9_home_appserver" with default driver
Creating volume "drupal9_data_database" with default driver
Creating volume "drupal9_home_database" with default driver
Creating drupal9_appserver_1 ... done
mkdir: cannot create directory '/user/.ssh': File exists
Stopping drupal9_appserver_1 ... done
Starting drupal9_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599  100   599    0     0   1923      0 --:--:-- --:--:-- --:--:--  1926
100 4673k  100 4673k    0     0  2746k      0  0:00:01  0:00:01 --:--:-- 4355k
 Drush Version   :  8.2.3 

Stopping drupal9_appserver_1 ... done
Starting drupal9_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  811k  100  811k    0     0   116k      0  0:00:06  0:00:06 --:--:--  173k
Stopping drupal9_appserver_1 ... done
Starting drupal9_appserver_1 ... done
Creating drupal9_database_1  ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            drupal9                   
 LOCATION        /home/user_name/drupal          
 SERVICES        appserver, database       
 APPSERVER URLS  https://localhost:32785   
                 http://localhost:32786    
                 http://drupal9.lndo.site  
                 https://drupal9.lndo.site 

===> Installing Drupal
require(/app/vendor/autoload.php): failed to open stream: No such file or directory autoload.php:14                                                                                                                                                  [warning]
PHP Fatal error:  require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php on line 14

Fatal error: require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php on line 14
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
Error: require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php, line 14
require(/app/vendor/autoload.php): failed to open stream: No such file or directory autoload.php:14                                                                                                                                                  [warning]
PHP Fatal error:  require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php on line 14

Fatal error: require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php on line 14
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
Error: require(): Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/autoload.php, line 14
```

**Comment by anavarre** [comment]
```
===> Pulling Composer dependencies
Your requirements could not be resolved to an installable set of packages.
===> Installing the latest Drush
Your requirements could not be resolved to an installable set of packages.
```

This is a different issue with your local Composer (I can't reproduce). You could try and replace this line https://github.com/anavarre/d9/blob/master/d9.py#L95 by

```
call(["composer", "install"])
```

This would make Composer verbose again, allowing you to better troubleshoot the issue.

**Comment by gitressa** [comment]
That did give some more info. Perhaps `--verbose` could be added as an extra option, for future easier debugging?

Anyway, here is the result:
```
$ ../d9/d9.py --install
===> Drupal 9 codebase detected
===> Git repository detected
===> Drupal 9 branch detected
===> composer.json detected
===> Pulling Composer dependencies
> Drupal\Composer\Composer::ensureComposerVersion
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/core 9.0.x-dev -> satisfiable by drupal/core[9.0.x-dev].
    - drupal/core 9.0.x-dev requires php >=7.3 -> your PHP version (7.2.24) does not satisfy that requirement.
  Problem 2
    - Installation request for drupal/core-project-message 9.0.x-dev -> satisfiable by drupal/core-project-message[9.0.x-dev].
    - drupal/core-project-message 9.0.x-dev requires php >=7.3.0 -> your PHP version (7.2.24) does not satisfy that requirement.
  Problem 3
    - Installation request for drupal/core-vendor-hardening 9.0.x-dev -> satisfiable by drupal/core-vendor-hardening[9.0.x-dev].
    - drupal/core-vendor-hardening 9.0.x-dev requires php >=7.3.0 -> your PHP version (7.2.24) does not satisfy that requirement.
```
... which makes sense, since I do have PHP 7.2.24 on my machine. But shouldn't Lando be able to bump up PHP versions to PHP 7.3?

**Comment by gitressa** [comment]
I'll try to install PHP 7.3 on my OS (Ubuntu 18.04) and see if it helps.

**Comment by gitressa** [comment]
[Installing PHP 7.3](https://phoenixnap.com/kb/install-php-7-on-ubuntu) on my host OS Ubuntu 18.04 took care of the issue, and the process completed.

I first tried changing the sequence of processes, putting `pull_dependencies()` after `Lando start` in the hope that it would check for Lando PHP version (7.3), not my OS (7.2), like this:
```
    check_requirements()
    check_drupal_version()
    check_git_repo()
    create_lando_file()
    start_app()
    pull_dependencies()
    install_drupal()
```
But sadly it found my OS version (7.2) which again made Composer complain.

A side note: I also could never make https work with Lando, so why not just use http://drupal9.lndo.site as `uri`, to avoid the warning? Is it because https is sometimes needed for development?

**Comment by anavarre** [comment]
> Perhaps --verbose could be added as an extra option, for future easier debugging?

Composer is really verbose, usually, so I was debating whether to leave it quiet (`-q` parameter) or leave the full output visible. I'm not opinionated. If that's easier I'm happy to remove the quiet parameter.

Anyway, it's now clear what is happening...and it shouldn't happen. I just tried to modify the `.lando.yml` file to require PHP 7.2 and immediately got:

```
[notice] Starting Drupal installation. This takes a while.

In install.core.inc line 2273:

PHP: 7.2.28                                                                                                         

Your PHP installation is too old. Drupal requires at least PHP <em class="placeholder">7.3.0</em>. (snip)
```

Even though my local PHP version is:

```
$ php -v
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
```

So it's working correctly and using the PHP version in the container used by Lando. I'm wondering why it wouldn't do this for you :open_mouth: 

> A side note: I also could never make https work with Lando, so why not just use http://drupal9.lndo.site as uri, to avoid the warning? Is it because https is sometimes needed for development?

I was trying to follow best practices, mostly, but since it's a) local and b) dev only, it's not a big deal to only use HTTP.

**Comment by gitressa** [comment]
> Composer is really verbose ...  If that's easier I'm happy to remove the quiet parameter.

I totally agree, it's quite verbose, so I think your decision of having quiet by default is the right one. But in cases like this, it would be great to be able to do `d9 --install --verbose`, but only if it's not too much hassle for you to implement.

I get different Composer as well as PHP versions, depending on if I run them with or without `lando` in front:

**Composer**
```
$ lando composer -V
Composer version 1.9.1 2019-11-01 17:20:17
$ composer -V
Composer version 1.9.3 2020-02-04 12:58:49
```

**PHP**
```
$ lando php -v
PHP 7.3.15 (cli) (built: Feb 26 2020 13:07:10) ( NTS )
$ php -v
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )

```

It seems that the d9 code checks the PHP version of the host OS, in stead of Lando, which would be the correct place to check, right? So it might work even with PHP 7.0 on my host OS if:

1. `pull_dependencies()` is run after `lando start` (second last) since it can't otherwise use Lando
2. It is run as `lando composer install`, not just `composer install`

> I was trying to follow best practices, mostly, but since it's a) local and b) dev only, it's not big deal to only use HTTP.

In that case I would personally prefer HTTP, and avoid the ugly warning.

**Comment by anavarre** [comment]
Hey, thanks for the feedback and PR. Sorry I didn't see it. See 9c4619b which tries to only invoke Composer via Lando.

**Comment by anavarre** [comment]
Also, see d4b3f2b which does not force HTTPS. There's a way in Lando to self-sign the SSL certificate so I might have to explore this option to get back to the https://drupal9.lndo.site URL at some point.

**Comment by gitressa** [comment]
Thanks for fixing the issues, the current version works quite well.

I have previously spend quite some time trying to got SSL working in Lando, but gave up after trying many different thing, and just used HTTP. But it would be awesome if you managed to get it working somehow.
